# Generated by Django 2.0.2 on 2018-02-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20180225_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alquiler',
            old_name='f_debuelta',
            new_name='comp_debuelta',
        ),
    ]
