# Generated by Django 2.0.2 on 2018-02-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20180225_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='update_at',
        ),
    ]
