# Generated by Django 2.0.2 on 2018-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20180225_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Correo',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
