# Generated by Django 2.0.2 on 2018-02-25 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_usuario_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='comp_debuelta',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='Fecha_devolucion',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='Pelicula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.peliculas'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
