# Generated by Django 2.0.2 on 2018-02-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20180225_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alquiler',
            old_name='Fecha_devolucion',
            new_name='Comprobante_devolucion',
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='fechaDevolucion',
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='fecha_Alquier',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='fechaDevolucion',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='fecha_Alquier',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
