# Generated by Django 2.0.2 on 2018-02-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20180225_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
